easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\User
        - App\Entity\Reservation
        - App\Entity\Movie
        - App\Entity\Session
        - App\Entity\Room
